
  package org.javastro.ivoacore.pgsphere.types;

    
    
/**
* a simple bounding box.
*
* dataType:  Box
*
* @author generated by https://github.com/ivoa/vo-dml tools
*/
      


  @jakarta.xml.bind.annotation.XmlAccessorType( jakarta.xml.bind.annotation.XmlAccessType.NONE )
  @jakarta.xml.bind.annotation.XmlType( name = "Box"
      

      )
  
@com.fasterxml.jackson.annotation.JsonTypeInfo (use = com.fasterxml.jackson.annotation.JsonTypeInfo.Id.NAME )
              
@org.ivoa.vodml.annotation.VoDml(id="adqlgeom:Box", role=org.ivoa.vodml.annotation.VodmlRole.dataType)
          

        @org.eclipse.microprofile.openapi.annotations.media.Schema(description="a simple bounding box")
    

      public  class Box extends Shape
       implements org.ivoa.vodml.jpa.JPAManipulations {
      

    /**
    * south-west edge of the box. : Attribute pos_sw : multiplicity 1
    *
    */
    
@org.ivoa.vodml.annotation.VoDml(id="adqlgeom:Box.pos_sw", role=org.ivoa.vodml.annotation.VodmlRole.attribute, type="adqlgeom:Point",typeRole=org.ivoa.vodml.annotation.VodmlRole.dataType)
          

        @org.eclipse.microprofile.openapi.annotations.media.Schema(description="south-west edge of the box")
    
    @jakarta.xml.bind.annotation.XmlElement( name = "pos_sw", required =true, type = Point.class)
            
                  
                      
    protected Point pos_sw;
        

    /**
    * north-east edge of the box. : Attribute pos_ne : multiplicity 1
    *
    */
    
@org.ivoa.vodml.annotation.VoDml(id="adqlgeom:Box.pos_ne", role=org.ivoa.vodml.annotation.VodmlRole.attribute, type="adqlgeom:Point",typeRole=org.ivoa.vodml.annotation.VodmlRole.dataType)
          

        @org.eclipse.microprofile.openapi.annotations.media.Schema(description="north-east edge of the box")
    
    @jakarta.xml.bind.annotation.XmlElement( name = "pos_ne", required =true, type = Point.class)
            
                  
                      
    protected Point pos_ne;
        

      /**
       * Creates a new Box
       */
      public Box() {
        super();
      }
      
        /**
        * full parameter constructor.
            
        *   @param pos_sw south-west edge of the box.
        *   @param pos_ne north-east edge of the box.
        */
        public  Box (
          final Point pos_sw, final Point pos_ne
        )
        {
            super();
           
                       this.pos_sw = pos_sw;
                   
                       this.pos_ne = pos_ne;
                   
          }
        
            /**
            * make a clone of the object taking into account current polymorhic type.
            * @return the cloned object.
            */
            public Shape copyMe()
                {
                   return new Box(this);
                }
            

        /**
        * Copy Constructor. Note that references will remain as is rather than be copied.
        * @param other the object to be copied.
        */
        public  Box ( final Box other)
        {
        
                super(other);
            
                    if (other.pos_sw != null )this.pos_sw= new Point(other.pos_sw);
                
                    if (other.pos_ne != null )this.pos_ne= new Point(other.pos_ne);
                

        }


        /**
        * Update this object with the content of the given object. Note that references will remain as is rather than be copied.
        * @param other the object to be copied.
        */
        public void updateUsing ( final Box other)
        {

        
                    if (other.pos_sw != null )this.pos_sw= new Point(other.pos_sw);
                
                    if (other.pos_ne != null )this.pos_ne= new Point(other.pos_ne);
                

        }

        
            /**
            * Constructor from supertype instance.
            * @param superinstance The supertype.
            
            * @param pos_sw south-west edge of the box.
            * @param pos_ne north-east edge of the box.
            */
            public  Box ( final Shape superinstance,final Point pos_sw,final Point pos_ne )
            {
            super (superinstance);
            
                        this.pos_sw = pos_sw;
                    
                        this.pos_ne = pos_ne;
                    

            }
        
        /**
        * Returns pos_sw Attribute.
        * @return pos_sw Attribute
        */
        
        public Point getPos_sw() {
        return (Point)this.pos_sw;
        }
        
        
        /**
        * Set pos_sw Attribute.
        * @param pPos_sw value to set
        */
        public void setPos_sw(final Point pPos_sw) {
        
        this.pos_sw = pPos_sw;
        }
        
        /**
        * fluent setter for pos_sw Attribute.
        * @param pPos_sw value to set
        * @return Box
        */
        public Box withPos_sw(final Point pPos_sw) {
        setPos_sw(pPos_sw);
        return this;
        }

    
        /**
        * Returns pos_ne Attribute.
        * @return pos_ne Attribute
        */
        
        public Point getPos_ne() {
        return (Point)this.pos_ne;
        }
        
        
        /**
        * Set pos_ne Attribute.
        * @param pPos_ne value to set
        */
        public void setPos_ne(final Point pPos_ne) {
        
        this.pos_ne = pPos_ne;
        }
        
        /**
        * fluent setter for pos_ne Attribute.
        * @param pPos_ne value to set
        * @return Box
        */
        public Box withPos_ne(final Point pPos_ne) {
        setPos_ne(pPos_ne);
        return this;
        }

    

        /**
          A builder class for Box, mainly for use in the functional builder pattern.
        */
        public static class BoxBuilder {
           


                   /**
                   * south-west edge of the box.
                   */
                   public Point pos_sw;
                           


                   /**
                   * north-east edge of the box.
                   */
                   public Point pos_ne;
                           

           private BoxBuilder with (java.util.function.Consumer <BoxBuilder> f)
           {
             f.accept(this);
             return this;
           }
           /**
           *  create a Box from this builder.
           *  @return an object initialized from the builder.
           */
           public Box create()
           {
             return new Box (
          
              pos_sw,pos_ne
              );
           }
         }
        /**
        *   create a Box in functional builder style.
        *  @param f the functional builder.
        *  @return an object initialized from the builder.
        */
         public static Box createBox (java.util.function.Consumer <BoxBuilder> f)
         {
             return new BoxBuilder().with(f).create();
         }
    
        @Override
        public void forceLoad() {
        
            super.forceLoad();
        
        }
     
          @Override
          public boolean equals(Object o_) {
          if (!(o_ instanceof Box oc_)) return false;
          
                  boolean retval = super.equals(o_) && java.util.Objects.equals(pos_sw,oc_.pos_sw)  && java.util.Objects.equals(pos_ne,oc_.pos_ne)
                  ;
              

          return retval;
          }

          @Override
          public int hashCode() {
          return java.util.Objects.hash(pos_sw,pos_ne);
          }
      
}
  