
  package org.javastro.ivoacore.pgsphere.types;

    
    
/**
* a circular region on the sky.
*
* dataType:  Circle
*
* @author generated by https://github.com/ivoa/vo-dml tools
*/


  @jakarta.xml.bind.annotation.XmlAccessorType( jakarta.xml.bind.annotation.XmlAccessType.NONE )
  @jakarta.xml.bind.annotation.XmlType( name = "Circle"
      

      )
  
@com.fasterxml.jackson.annotation.JsonTypeInfo (use = com.fasterxml.jackson.annotation.JsonTypeInfo.Id.NAME )
              
@org.ivoa.vodml.annotation.VoDml(id="adqlgeom:Circle", role=org.ivoa.vodml.annotation.VodmlRole.dataType)
          

        @org.eclipse.microprofile.openapi.annotations.media.Schema(description="a circular region on the sky")
    

      public  class Circle extends Shape
       implements org.ivoa.vodml.jpa.JPAManipulations {
      

    /**
    * the centre of the circle. : Attribute center : multiplicity 1
    *
    */
    
@org.ivoa.vodml.annotation.VoDml(id="adqlgeom:Circle.center", role=org.ivoa.vodml.annotation.VodmlRole.attribute, type="adqlgeom:Point",typeRole=org.ivoa.vodml.annotation.VodmlRole.dataType)
          

        @org.eclipse.microprofile.openapi.annotations.media.Schema(description="the centre of the circle")
    
    @jakarta.xml.bind.annotation.XmlElement( name = "center", required =true, type = Point.class)
            
                  
                      
    protected Point center;
        

    /**
    * the radius of the circle. : Attribute radius : multiplicity 1
    *
    */
    
@org.ivoa.vodml.annotation.VoDml(id="adqlgeom:Circle.radius", role=org.ivoa.vodml.annotation.VodmlRole.attribute, type="ivoa:real",typeRole=org.ivoa.vodml.annotation.VodmlRole.primitiveType)
          

        @org.eclipse.microprofile.openapi.annotations.media.Schema(description="the radius of the circle")
    
    @jakarta.xml.bind.annotation.XmlElement( name = "radius", required =true, type = Double.class)
            
        
        
                            
    protected Double radius;
        

      /**
       * Creates a new Circle
       */
      public Circle() {
        super();
      }
      
        /**
        * full parameter constructor.
            
        *   @param center the centre of the circle.
        *   @param radius the radius of the circle.
        */
        public  Circle (
          final Point center, final Double radius
        )
        {
            super();
           
                       this.center = center;
                   
                       this.radius = radius;
                   
          }
        
            /**
            * make a clone of the object taking into account current polymorhic type.
            * @return the cloned object.
            */
            public Shape copyMe()
                {
                   return new Circle(this);
                }
            

        /**
        * Copy Constructor. Note that references will remain as is rather than be copied.
        * @param other the object to be copied.
        */
        public  Circle ( final Circle other)
        {
        
                super(other);
            
                    if (other.center != null )this.center= new Point(other.center);
                
                  this.radius= other.radius;
            

        }


        /**
        * Update this object with the content of the given object. Note that references will remain as is rather than be copied.
        * @param other the object to be copied.
        */
        public void updateUsing ( final Circle other)
        {

        
                    if (other.center != null )this.center= new Point(other.center);
                
                  this.radius= other.radius;
            

        }

        
            /**
            * Constructor from supertype instance.
            * @param superinstance The supertype.
            
            * @param center the centre of the circle.
            * @param radius the radius of the circle.
            */
            public  Circle ( final Shape superinstance,final Point center,final Double radius )
            {
            super (superinstance);
            
                        this.center = center;
                    
                        this.radius = radius;
                    

            }
        
        /**
        * Returns center Attribute.
        * @return center Attribute
        */
        
        public Point getCenter() {
        return (Point)this.center;
        }
        
        
        /**
        * Set center Attribute.
        * @param pCenter value to set
        */
        public void setCenter(final Point pCenter) {
        
        this.center = pCenter;
        }
        
        /**
        * fluent setter for center Attribute.
        * @param pCenter value to set
        * @return Circle
        */
        public Circle withCenter(final Point pCenter) {
        setCenter(pCenter);
        return this;
        }

    
        /**
        * Returns radius Attribute.
        * @return radius Attribute
        */
        
        public Double getRadius() {
        return (Double)this.radius;
        }
        
        
        /**
        * Set radius Attribute.
        * @param pRadius value to set
        */
        public void setRadius(final Double pRadius) {
        
        this.radius = pRadius;
        }
        
        /**
        * fluent setter for radius Attribute.
        * @param pRadius value to set
        * @return Circle
        */
        public Circle withRadius(final Double pRadius) {
        setRadius(pRadius);
        return this;
        }

    

        /**
          A builder class for Circle, mainly for use in the functional builder pattern.
        */
        public static class CircleBuilder {
           


                   /**
                   * the centre of the circle.
                   */
                   public Point center;
                           


                   /**
                   * the radius of the circle.
                   */
                   public Double radius;
                           

           private CircleBuilder with (java.util.function.Consumer <CircleBuilder> f)
           {
             f.accept(this);
             return this;
           }
           /**
           *  create a Circle from this builder.
           *  @return an object initialized from the builder.
           */
           public Circle create()
           {
             return new Circle (
          
              center,radius
              );
           }
         }
        /**
        *   create a Circle in functional builder style.
        *  @param f the functional builder.
        *  @return an object initialized from the builder.
        */
         public static Circle createCircle (java.util.function.Consumer <CircleBuilder> f)
         {
             return new CircleBuilder().with(f).create();
         }
    
        @Override
        public void forceLoad() {
        
            super.forceLoad();
        
        }
     
          @Override
          public boolean equals(Object o_) {
          if (!(o_ instanceof Circle oc_)) return false;
          
                  boolean retval = super.equals(o_) && java.util.Objects.equals(center,oc_.center)  && java.util.Objects.equals(radius,oc_.radius)
                  ;
              

          return retval;
          }

          @Override
          public int hashCode() {
          return java.util.Objects.hash(center,radius);
          }
      
}
  