
  package org.javastro.ivoacore.pgsphere.types;

    
    
/**
* an elliptical region on the sky.
*
* dataType:  Ellipse
*
* @author generated by https://github.com/ivoa/vo-dml tools
*/
      


  @jakarta.xml.bind.annotation.XmlAccessorType( jakarta.xml.bind.annotation.XmlAccessType.NONE )
  @jakarta.xml.bind.annotation.XmlType( name = "Ellipse"
      

      )
  
@com.fasterxml.jackson.annotation.JsonTypeInfo (use = com.fasterxml.jackson.annotation.JsonTypeInfo.Id.NAME )
              
@org.ivoa.vodml.annotation.VoDml(id="adqlgeom:Ellipse", role=org.ivoa.vodml.annotation.VodmlRole.dataType)
          

        @org.eclipse.microprofile.openapi.annotations.media.Schema(description="an elliptical region on the sky")
    

      public  class Ellipse extends Shape
       implements org.ivoa.vodml.jpa.JPAManipulations {
      

    /**
    * major axis size in radians. : Attribute major_axis : multiplicity 1
    *
    */
    
@org.ivoa.vodml.annotation.VoDml(id="adqlgeom:Ellipse.major_axis", role=org.ivoa.vodml.annotation.VodmlRole.attribute, type="ivoa:real",typeRole=org.ivoa.vodml.annotation.VodmlRole.primitiveType)
          

        @org.eclipse.microprofile.openapi.annotations.media.Schema(description="major axis size in radians")
    
    @jakarta.xml.bind.annotation.XmlElement( name = "major_axis", required =true, type = Double.class)
            
        
        
                            
    protected Double major_axis;
        

    /**
    * minor axis size in radians. : Attribute minor_axis : multiplicity 1
    *
    */
    
@org.ivoa.vodml.annotation.VoDml(id="adqlgeom:Ellipse.minor_axis", role=org.ivoa.vodml.annotation.VodmlRole.attribute, type="ivoa:real",typeRole=org.ivoa.vodml.annotation.VodmlRole.primitiveType)
          

        @org.eclipse.microprofile.openapi.annotations.media.Schema(description="minor axis size in radians")
    
    @jakarta.xml.bind.annotation.XmlElement( name = "minor_axis", required =true, type = Double.class)
            
        
        
                            
    protected Double minor_axis;
        

    /**
    * the centre of the circle. : Attribute center : multiplicity 1
    *
    */
    
@org.ivoa.vodml.annotation.VoDml(id="adqlgeom:Ellipse.center", role=org.ivoa.vodml.annotation.VodmlRole.attribute, type="adqlgeom:Point",typeRole=org.ivoa.vodml.annotation.VodmlRole.dataType)
          

        @org.eclipse.microprofile.openapi.annotations.media.Schema(description="the centre of the circle")
    
    @jakarta.xml.bind.annotation.XmlElement( name = "center", required =true, type = Point.class)
            
                  
                      
    protected Point center;
        

    /**
    * The position angle pos is defined as a counterclockwise rotation around the ellipse center and is zero, if the ellipse is “parallel to the equator”. : Attribute pos_angle : multiplicity 1
    *
    */
    
@org.ivoa.vodml.annotation.VoDml(id="adqlgeom:Ellipse.pos_angle", role=org.ivoa.vodml.annotation.VodmlRole.attribute, type="ivoa:real",typeRole=org.ivoa.vodml.annotation.VodmlRole.primitiveType)
          

        @org.eclipse.microprofile.openapi.annotations.media.Schema(description="The position angle pos is defined as a counterclockwise rotation around the ellipse center and is zero, if the ellipse is “parallel to the equator”")
    
    @jakarta.xml.bind.annotation.XmlElement( name = "pos_angle", required =true, type = Double.class)
            
        
        
                            
    protected Double pos_angle;
        

      /**
       * Creates a new Ellipse
       */
      public Ellipse() {
        super();
      }
      
        /**
        * full parameter constructor.
            
        *   @param major_axis major axis size in radians.
        *   @param minor_axis minor axis size in radians.
        *   @param center the centre of the circle.
        *   @param pos_angle The position angle pos is defined as a counterclockwise rotation around the ellipse center and is zero, if the ellipse is “parallel to the equator”.
        */
        public  Ellipse (
          final Double major_axis, final Double minor_axis, final Point center, final Double pos_angle
        )
        {
            super();
           
                       this.major_axis = major_axis;
                   
                       this.minor_axis = minor_axis;
                   
                       this.center = center;
                   
                       this.pos_angle = pos_angle;
                   
          }
        
            /**
            * make a clone of the object taking into account current polymorhic type.
            * @return the cloned object.
            */
            public Shape copyMe()
                {
                   return new Ellipse(this);
                }
            

        /**
        * Copy Constructor. Note that references will remain as is rather than be copied.
        * @param other the object to be copied.
        */
        public  Ellipse ( final Ellipse other)
        {
        
                super(other);
            
                  this.major_axis= other.major_axis;
            
                  this.minor_axis= other.minor_axis;
            
                    if (other.center != null )this.center= new Point(other.center);
                
                  this.pos_angle= other.pos_angle;
            

        }


        /**
        * Update this object with the content of the given object. Note that references will remain as is rather than be copied.
        * @param other the object to be copied.
        */
        public void updateUsing ( final Ellipse other)
        {

        
                  this.major_axis= other.major_axis;
            
                  this.minor_axis= other.minor_axis;
            
                    if (other.center != null )this.center= new Point(other.center);
                
                  this.pos_angle= other.pos_angle;
            

        }

        
            /**
            * Constructor from supertype instance.
            * @param superinstance The supertype.
            
            * @param major_axis major axis size in radians.
            * @param minor_axis minor axis size in radians.
            * @param center the centre of the circle.
            * @param pos_angle The position angle pos is defined as a counterclockwise rotation around the ellipse center and is zero, if the ellipse is “parallel to the equator”.
            */
            public  Ellipse ( final Shape superinstance,final Double major_axis,final Double minor_axis,final Point center,final Double pos_angle )
            {
            super (superinstance);
            
                        this.major_axis = major_axis;
                    
                        this.minor_axis = minor_axis;
                    
                        this.center = center;
                    
                        this.pos_angle = pos_angle;
                    

            }
        
        /**
        * Returns major_axis Attribute.
        * @return major_axis Attribute
        */
        
        public Double getMajor_axis() {
        return (Double)this.major_axis;
        }
        
        
        /**
        * Set major_axis Attribute.
        * @param pMajor_axis value to set
        */
        public void setMajor_axis(final Double pMajor_axis) {
        
        this.major_axis = pMajor_axis;
        }
        
        /**
        * fluent setter for major_axis Attribute.
        * @param pMajor_axis value to set
        * @return Ellipse
        */
        public Ellipse withMajor_axis(final Double pMajor_axis) {
        setMajor_axis(pMajor_axis);
        return this;
        }

    
        /**
        * Returns minor_axis Attribute.
        * @return minor_axis Attribute
        */
        
        public Double getMinor_axis() {
        return (Double)this.minor_axis;
        }
        
        
        /**
        * Set minor_axis Attribute.
        * @param pMinor_axis value to set
        */
        public void setMinor_axis(final Double pMinor_axis) {
        
        this.minor_axis = pMinor_axis;
        }
        
        /**
        * fluent setter for minor_axis Attribute.
        * @param pMinor_axis value to set
        * @return Ellipse
        */
        public Ellipse withMinor_axis(final Double pMinor_axis) {
        setMinor_axis(pMinor_axis);
        return this;
        }

    
        /**
        * Returns center Attribute.
        * @return center Attribute
        */
        
        public Point getCenter() {
        return (Point)this.center;
        }
        
        
        /**
        * Set center Attribute.
        * @param pCenter value to set
        */
        public void setCenter(final Point pCenter) {
        
        this.center = pCenter;
        }
        
        /**
        * fluent setter for center Attribute.
        * @param pCenter value to set
        * @return Ellipse
        */
        public Ellipse withCenter(final Point pCenter) {
        setCenter(pCenter);
        return this;
        }

    
        /**
        * Returns pos_angle Attribute.
        * @return pos_angle Attribute
        */
        
        public Double getPos_angle() {
        return (Double)this.pos_angle;
        }
        
        
        /**
        * Set pos_angle Attribute.
        * @param pPos_angle value to set
        */
        public void setPos_angle(final Double pPos_angle) {
        
        this.pos_angle = pPos_angle;
        }
        
        /**
        * fluent setter for pos_angle Attribute.
        * @param pPos_angle value to set
        * @return Ellipse
        */
        public Ellipse withPos_angle(final Double pPos_angle) {
        setPos_angle(pPos_angle);
        return this;
        }

    

        /**
          A builder class for Ellipse, mainly for use in the functional builder pattern.
        */
        public static class EllipseBuilder {
           


                   /**
                   * major axis size in radians.
                   */
                   public Double major_axis;
                           


                   /**
                   * minor axis size in radians.
                   */
                   public Double minor_axis;
                           


                   /**
                   * the centre of the circle.
                   */
                   public Point center;
                           


                   /**
                   * The position angle pos is defined as a counterclockwise rotation around the ellipse center and is zero, if the ellipse is “parallel to the equator”.
                   */
                   public Double pos_angle;
                           

           private EllipseBuilder with (java.util.function.Consumer <EllipseBuilder> f)
           {
             f.accept(this);
             return this;
           }
           /**
           *  create a Ellipse from this builder.
           *  @return an object initialized from the builder.
           */
           public Ellipse create()
           {
             return new Ellipse (
          
              major_axis,minor_axis,center,pos_angle
              );
           }
         }
        /**
        *   create a Ellipse in functional builder style.
        *  @param f the functional builder.
        *  @return an object initialized from the builder.
        */
         public static Ellipse createEllipse (java.util.function.Consumer <EllipseBuilder> f)
         {
             return new EllipseBuilder().with(f).create();
         }
    
        @Override
        public void forceLoad() {
        
            super.forceLoad();
        
        }
     
          @Override
          public boolean equals(Object o_) {
          if (!(o_ instanceof Ellipse oc_)) return false;
          
                  boolean retval = super.equals(o_) && java.util.Objects.equals(major_axis,oc_.major_axis)  && java.util.Objects.equals(minor_axis,oc_.minor_axis)  && java.util.Objects.equals(center,oc_.center)  && java.util.Objects.equals(pos_angle,oc_.pos_angle)
                  ;
              

          return retval;
          }

          @Override
          public int hashCode() {
          return java.util.Objects.hash(major_axis,minor_axis,center,pos_angle);
          }
      
}
  