
  package org.javastro.ivoacore.pgsphere.types;


  import java.util.regex.Matcher;
  import java.util.regex.Pattern;

  /**
* location on the sky in spherical coordinates.
*
* dataType:  Point
*
* @author generated by https://github.com/ivoa/vo-dml tools
*/
      


  @jakarta.xml.bind.annotation.XmlAccessorType( jakarta.xml.bind.annotation.XmlAccessType.NONE )
  @jakarta.xml.bind.annotation.XmlType( name = "Point"
      

      )
  
@com.fasterxml.jackson.annotation.JsonTypeInfo (use = com.fasterxml.jackson.annotation.JsonTypeInfo.Id.NONE )
              
//@jakarta.xml.bind.annotation.XmlRootElement( name = "Point")
      
@org.ivoa.vodml.annotation.VoDml(id="adqlgeom:Point", role=org.ivoa.vodml.annotation.VodmlRole.dataType)
          

        @org.eclipse.microprofile.openapi.annotations.media.Schema(description="location on the sky in spherical coordinates")
    

      public  class Point
       implements org.ivoa.vodml.jpa.JPAManipulations {
      

    /**
    * longitude angle. : Attribute alpha : multiplicity 1
    *
    */
    
@org.ivoa.vodml.annotation.VoDml(id="adqlgeom:Point.alpha", role=org.ivoa.vodml.annotation.VodmlRole.attribute, type="ivoa:real",typeRole=org.ivoa.vodml.annotation.VodmlRole.primitiveType)
          

        @org.eclipse.microprofile.openapi.annotations.media.Schema(description="longitude angle")
    
    @jakarta.xml.bind.annotation.XmlElement( name = "alpha", required =true, type = Double.class)
            
        
        
                            
    protected Double alpha;
        

    /**
    * latitude angle. : Attribute delta : multiplicity 1
    *
    */
    
@org.ivoa.vodml.annotation.VoDml(id="adqlgeom:Point.delta", role=org.ivoa.vodml.annotation.VodmlRole.attribute, type="ivoa:real",typeRole=org.ivoa.vodml.annotation.VodmlRole.primitiveType)
          

        @org.eclipse.microprofile.openapi.annotations.media.Schema(description="latitude angle")
    
    @jakarta.xml.bind.annotation.XmlElement( name = "delta", required =true, type = Double.class)
            
        
        
                            
    protected Double delta;
        

      /**
       * Creates a new Point
       */
      public Point() {
        super();
      }
      
        /**
        * full parameter constructor.
            
        *   @param alpha longitude angle.
        *   @param delta latitude angle.
        */
        public  Point (
          final Double alpha, final Double delta
        )
        {
            super();
           
                       this.alpha = alpha;
                   
                       this.delta = delta;
                   
          }
        

        /**
        * Copy Constructor. Note that references will remain as is rather than be copied.
        * @param other the object to be copied.
        */
        public  Point ( final Point other)
        {
        
                super ();
            
                  this.alpha= other.alpha;
            
                  this.delta= other.delta;
            

        }


        /**
        * Update this object with the content of the given object. Note that references will remain as is rather than be copied.
        * @param other the object to be copied.
        */
        public void updateUsing ( final Point other)
        {

        
                  this.alpha= other.alpha;
            
                  this.delta= other.delta;
            

        }

        
        /**
        * Returns alpha Attribute.
        * @return alpha Attribute
        */
        
        public Double getAlpha() {
        return (Double)this.alpha;
        }
        
        
        /**
        * Set alpha Attribute.
        * @param pAlpha value to set
        */
        public void setAlpha(final Double pAlpha) {
        
        this.alpha = pAlpha;
        }
        
        /**
        * fluent setter for alpha Attribute.
        * @param pAlpha value to set
        * @return Point
        */
        public Point withAlpha(final Double pAlpha) {
        setAlpha(pAlpha);
        return this;
        }

    
        /**
        * Returns delta Attribute.
        * @return delta Attribute
        */
        
        public Double getDelta() {
        return (Double)this.delta;
        }
        
        
        /**
        * Set delta Attribute.
        * @param pDelta value to set
        */
        public void setDelta(final Double pDelta) {
        
        this.delta = pDelta;
        }
        
        /**
        * fluent setter for delta Attribute.
        * @param pDelta value to set
        * @return Point
        */
        public Point withDelta(final Double pDelta) {
        setDelta(pDelta);
        return this;
        }

    

        /**
          A builder class for Point, mainly for use in the functional builder pattern.
        */
        public static class PointBuilder {
           


                   /**
                   * longitude angle.
                   */
                   public Double alpha;
                           


                   /**
                   * latitude angle.
                   */
                   public Double delta;
                           

           private PointBuilder with (java.util.function.Consumer <PointBuilder> f)
           {
             f.accept(this);
             return this;
           }
           /**
           *  create a Point from this builder.
           *  @return an object initialized from the builder.
           */
           public Point create()
           {
             return new Point (
          
              alpha,delta
              );
           }
         }
        /**
        *   create a Point in functional builder style.
        *  @param f the functional builder.
        *  @return an object initialized from the builder.
        */
         public static Point createPoint (java.util.function.Consumer <PointBuilder> f)
         {
             return new PointBuilder().with(f).create();
         }
    
        @Override
        public void forceLoad() {
        
        }
     
          @Override
          public boolean equals(Object o_) {
          if (!(o_ instanceof Point oc_)) return false;
          
                  boolean retval = java.util.Objects.equals(alpha,oc_.alpha)  && java.util.Objects.equals(delta,oc_.delta)
                  ;
              

          return retval;
          }

          @Override
          public int hashCode() {
          return java.util.Objects.hash(alpha,delta);
          }





  }
  