
  package org.javastro.ivoacore.pgsphere.types;

    
    
/**
* a simple polygon region on the sky defined a sequence of points connected by great-circle segments.
*
* dataType:  Polygon
*
* @author generated by https://github.com/ivoa/vo-dml tools
*/
      


  @jakarta.xml.bind.annotation.XmlAccessorType( jakarta.xml.bind.annotation.XmlAccessType.NONE )
  @jakarta.xml.bind.annotation.XmlType( name = "Polygon"
      

      )
  
@com.fasterxml.jackson.annotation.JsonTypeInfo (use = com.fasterxml.jackson.annotation.JsonTypeInfo.Id.NAME )
              
@org.ivoa.vodml.annotation.VoDml(id="adqlgeom:Polygon", role=org.ivoa.vodml.annotation.VodmlRole.dataType)
          

        @org.eclipse.microprofile.openapi.annotations.media.Schema(description="a simple polygon region on the sky defined a sequence of points connected by great-circle segments")
    

      public  class Polygon extends Shape
       implements org.ivoa.vodml.jpa.JPAManipulations {
      

    /**
    * the points that make up the polygon. : Attribute points : multiplicity 1..*
    *
    */
    
@org.ivoa.vodml.annotation.VoDml(id="adqlgeom:Polygon.points", role=org.ivoa.vodml.annotation.VodmlRole.attribute, type="adqlgeom:Point",typeRole=org.ivoa.vodml.annotation.VodmlRole.dataType)
          

        @org.eclipse.microprofile.openapi.annotations.media.Schema(description="the points that make up the polygon")
    
                                @jakarta.xml.bind.annotation.XmlElementWrapper( name = "points")
                                @jakarta.xml.bind.annotation.XmlElement( name = "point", required = true, type = Point.class)
                            
      
      
      
               
    protected java.util.List<Point> points = new java.util.ArrayList<>();
        

      /**
       * Creates a new Polygon
       */
      public Polygon() {
        super();
      }
      
        /**
        * full parameter constructor.
            
        *   @param points the points that make up the polygon.
        */
        public  Polygon (
          final java.util.List<Point> points
        )
        {
            super();
           
                       this.points = points;
                   
          }
        
            /**
            * make a clone of the object taking into account current polymorhic type.
            * @return the cloned object.
            */
            public Shape copyMe()
                {
                   return new Polygon(this);
                }
            

        /**
        * Copy Constructor. Note that references will remain as is rather than be copied.
        * @param other the object to be copied.
        */
        public  Polygon ( final Polygon other)
        {
        
                super(other);
            

                
                if (other.points != null ) {
                this.points = other.points.stream().map(s -> new Point((Point)s )).collect(java.util.stream.Collectors.toList());
                    

                }
            

        }


        /**
        * Update this object with the content of the given object. Note that references will remain as is rather than be copied.
        * @param other the object to be copied.
        */
        public void updateUsing ( final Polygon other)
        {

        

                
                if (other.points != null ) {
                this.points = other.points.stream().map(s -> new Point((Point)s )).collect(java.util.stream.Collectors.toList());
                    

                }
            

        }

        
            /**
            * Constructor from supertype instance.
            * @param superinstance The supertype.
            
            * @param points the points that make up the polygon.
            */
            public  Polygon ( final Shape superinstance,final java.util.List<Point> points )
            {
            super (superinstance);
            
                        this.points = points;
                    

            }
        
        /**
        * Returns points Attribute.
        * @return points Attribute
        */
        @SuppressWarnings("unchecked")
        public java.util.List<Point> getPoints() {
        return (java.util.List<Point>)this.points;
        }
        
        
        /**
        * Set points Attribute.
        * @param pPoints value to set
        */
        public void setPoints(final java.util.List<Point> pPoints) {
        
        this.points = pPoints;
        }
        
        /**
        * fluent setter for points Attribute.
        * @param pPoints value to set
        * @return Polygon
        */
        public Polygon withPoints(final java.util.List<Point> pPoints) {
        setPoints(pPoints);
        return this;
        }

    

        /**
          A builder class for Polygon, mainly for use in the functional builder pattern.
        */
        public static class PolygonBuilder {
           


                   /**
                   * the points that make up the polygon.
                   */
                   public java.util.List<Point> points;
                           

           private PolygonBuilder with (java.util.function.Consumer <PolygonBuilder> f)
           {
             f.accept(this);
             return this;
           }
           /**
           *  create a Polygon from this builder.
           *  @return an object initialized from the builder.
           */
           public Polygon create()
           {
             return new Polygon (
          
              points
              );
           }
         }
        /**
        *   create a Polygon in functional builder style.
        *  @param f the functional builder.
        *  @return an object initialized from the builder.
        */
         public static Polygon createPolygon (java.util.function.Consumer <PolygonBuilder> f)
         {
             return new PolygonBuilder().with(f).create();
         }
    
        @Override
        public void forceLoad() {
        
            super.forceLoad();
        
        }
     
          @Override
          public boolean equals(Object o_) {
          if (!(o_ instanceof Polygon oc_)) return false;
          
                  boolean retval = super.equals(o_) && java.util.Objects.equals(points,oc_.points)
                  ;
              

          return retval;
          }

          @Override
          public int hashCode() {
          return java.util.Objects.hash(points);
          }
      
}
  