
  package org.javastro.ivoacore.pgsphere.types;

    
    
/**
* base type of all shapes.
*
* dataType:  Shape
*
* @author generated by https://github.com/ivoa/vo-dml tools
*/
      



  @jakarta.xml.bind.annotation.XmlAccessorType( jakarta.xml.bind.annotation.XmlAccessType.NONE )
  @jakarta.xml.bind.annotation.XmlType( name = "Shape"
      

      )
   
  @jakarta.xml.bind.annotation.XmlSeeAlso({ Circle.class,Ellipse.class,Polygon.class,Box.class  })
  @com.fasterxml.jackson.annotation.JsonSubTypes({
          @com.fasterxml.jackson.annotation.JsonSubTypes.Type(value=Circle.class,name="adqlgeom:Circle"),@com.fasterxml.jackson.annotation.JsonSubTypes.Type(value=Ellipse.class,name="adqlgeom:Ellipse"),@com.fasterxml.jackson.annotation.JsonSubTypes.Type(value=Polygon.class,name="adqlgeom:Polygon"),@com.fasterxml.jackson.annotation.JsonSubTypes.Type(value=Box.class,name="adqlgeom:Box")
  })
          
  @com.fasterxml.jackson.databind.annotation.JsonTypeIdResolver(value = org.ivoa.vodml.json.VodmlTypeResolver.class)
   //   @com.fasterxml.jackson.annotation.JsonTypeInfo (use = com.fasterxml.jackson.annotation.JsonTypeInfo.Id.NAME, include = com.fasterxml.jackson.annotation.JsonTypeInfo.As.WRAPPER_OBJECT )
  @com.fasterxml.jackson.annotation.JsonTypeInfo (use = com.fasterxml.jackson.annotation.JsonTypeInfo.Id.NAME, include = com.fasterxml.jackson.annotation.JsonTypeInfo.As.PROPERTY,property = "@type" )
  
//@jakarta.xml.bind.annotation.XmlRootElement( name = "Shape")
      
@org.ivoa.vodml.annotation.VoDml(id="adqlgeom:Shape", role=org.ivoa.vodml.annotation.VodmlRole.dataType)
          

        @org.eclipse.microprofile.openapi.annotations.media.Schema(description="base type of all shapes")
    

      public abstract class Shape 
       implements org.ivoa.vodml.jpa.JPAManipulations {
      

      /**
       * Creates a new Shape
       */
      public Shape() {
        super();
      }
      
            /**
            * make a clone of the object taking into account current polymorhic type.
            * @return the cloned object.
            */
            abstract public Shape copyMe();

        /**
        * Copy Constructor. Note that references will remain as is rather than be copied.
        * @param other the object to be copied.
        */
        public  Shape ( final Shape other)
        {
        
                super ();
            

        }


        /**
        * Update this object with the content of the given object. Note that references will remain as is rather than be copied.
        * @param other the object to be copied.
        */
        public void updateUsing ( final Shape other)
        {

        

        }

        
        @Override
        public void forceLoad() {
        
        }
     
          @Override
          public boolean equals(Object o_) {
          if (!(o_ instanceof Shape oc_)) return false;
          
                  boolean retval =  true;
              

          return retval;
          }

          @Override
          public int hashCode() {
          return java.util.Objects.hash();
          }
      
}
  